sudo: true
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d
- docker build -t stella .
script:
- docker images stella
deploy:
  provider: script
  skip_cleanup: true
  script: sh deploy/deploy.sh
  on:
    tags: true
addons:
  ssh_known_hosts: vps.adi.wtf
