sudo: true
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- docker build -t stella .
script:
- docker images stella
after_success:
- make image
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    tags: true
